lab_7/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	 url(r'^$', index, name='index'),
	 url(r'^add-friend/$', add_friend, name='add-friend'),
	 url(r'^validate-npm/$', validate_npm, name='validate-npm'),
	 url(r'^delete-friend/$', delete_friend, name='delete-friend'),
	 url(r'^get-friend-list/$', friend_list_json, name='get-friend-list'),
	# additional
	 url(r'^friend-list/$', friend_list, name='friend-list')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

import lab_7.urls as lab_7
import lab_9.urls as lab_9

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    #url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    #url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    #url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    #url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    #url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    #url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    #url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    #url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    #url(r'^$', RedirectView.as_view(url='/lab-10/movie/list')),
]

lab_7/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)

    def as_dict(self):
        return {
            "friend_name": self.friend_name,
            "npm": self.npm,
        }

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Friend
from .csui_helper import CSUIhelper
# import os

# by guhkun
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

response = {}
csui_helper = CSUIhelper()

def index(request):
    response['author']= "guhkunganteng"
    response['friend_list'] = Friend.objects.all()
    all_mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    html = 'lab_7/lab_7.html'

    #untuk pagination : https://docs.djangoproject.com/en/1.11/topics/pagination/
    paginator = Paginator(all_mahasiswa_list, 10)
    page = request.GET.get('page')
    try:
        mahasiswa_list = paginator.page(page)
    except PageNotAnInteger:
        mahasiswa_list = paginator.page(1)
    except EmptyPage:
        mahasiswa_list = paginator.page(paginator.num_pages)

    response['mahasiswa_list'] = mahasiswa_list
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def friend_list_json(request): # update
    print ("method friend list json")
    friends = [obj.as_dict() for obj in Friend.objects.all()]
    return JsonResponse({"results": friends}, content_type='application/json')

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        return JsonResponse(friend.as_dict())

@csrf_exempt
def delete_friend(request):
    print ("call delete friend")
    friend_id = request.POST['friend_id']
    print ("friend_id = ", friend_id)
    st = Friend.objects.get(npm=friend_id).delete()
    print ("st = ", st)

    return HttpResponseRedirect('/lab-7/')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm=npm).exists()
    }
    return JsonResponse(data)

lab_7/templates/lab_7/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<div class="row" style="text-align:center">
    <p>Made with Love by {{author}}</p>
</div>

lab_7/templates/lab_7/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
<!-- <nav> -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'lab-7:index' %}">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="{% url 'lab-7:friend-list' %}"> Friend List </a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>